name: Actualización chiste del README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Actualizar chistes del README.md
        run: npm run chiste-malo

      - name: Configurar Git y hacer push con token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "solidsnk86"
          git config user.email "calcagni.gabriel86@gmail.com"

          # Actualizar el remoto con autenticación
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/PowerSystem2024/doubleCommit.ts.git

          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖[neoBot] Se ha actualizado el chiste 😭"
          git push origin main
